### ISSUE TITLE
Intra-cluster networking is broken on microk8s

### ISSUE THREAD

**Issue by nightkr** [stackabletech/zookeeper-operator#627]
### Affected version

0.13.0

### Current and expected behavior

ZooKeeper crashes on startup with the following log messages:

```
2023-02-02 13:36:54,253 [myid:] - INFO  [ListenerHandler-simple-zk-server-default-0.simple-zk-server-default.default.svc.cluster.local:3888:o.a.z.s.q.QuorumCnxManager$Listener$ListenerHandler@1133] - Creating TLS-only quorum server socket
2023-02-02 13:36:54,254 [myid:] - ERROR [ListenerHandler-simple-zk-server-default-0.simple-zk-server-default.default.svc.cluster.local:3888:o.a.z.s.q.QuorumCnxManager$Listener$ListenerHandler@1099] - Exception while listening to address simple-zk-server-default-0.simple-zk-server-default.default.svc.cluster.local:3888
java.net.SocketException: Unresolved address
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.createNewServerSocket(QuorumCnxManager.java:1141)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.acceptConnections(QuorumCnxManager.java:1070)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.run(QuorumCnxManager.java:1039)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Additional context

This is using secret-operator from https://github.com/stackabletech/secret-operator/pull/232, otherwise the ZK pods aren't even able to start.

### Environment

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-19T02:26:55Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-09T15:09:52Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
MicroK8s v1.26.0 revision 4390

### Would you like to work on fixing this bug?

None

**Comment by nightkr** [comment]
This seems to be due to missing the `dns` addon, installing that lets the ZK pods become ready!
